require('plugins')
require("nvim-tree").setup()
--require("zephyr")
require("onedark").load()
require("keybindings")
require("lualine").setup()
require("dashboard")
require("plugin-config/bufferline")
